// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package grpcservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DumpReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpReq) Reset()         { *m = DumpReq{} }
func (m *DumpReq) String() string { return proto.CompactTextString(m) }
func (*DumpReq) ProtoMessage()    {}
func (*DumpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *DumpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpReq.Unmarshal(m, b)
}
func (m *DumpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpReq.Marshal(b, m, deterministic)
}
func (m *DumpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpReq.Merge(m, src)
}
func (m *DumpReq) XXX_Size() int {
	return xxx_messageInfo_DumpReq.Size(m)
}
func (m *DumpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpReq.DiscardUnknown(m)
}

var xxx_messageInfo_DumpReq proto.InternalMessageInfo

type DumpItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpItem) Reset()         { *m = DumpItem{} }
func (m *DumpItem) String() string { return proto.CompactTextString(m) }
func (*DumpItem) ProtoMessage()    {}
func (*DumpItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *DumpItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpItem.Unmarshal(m, b)
}
func (m *DumpItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpItem.Marshal(b, m, deterministic)
}
func (m *DumpItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpItem.Merge(m, src)
}
func (m *DumpItem) XXX_Size() int {
	return xxx_messageInfo_DumpItem.Size(m)
}
func (m *DumpItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpItem.DiscardUnknown(m)
}

var xxx_messageInfo_DumpItem proto.InternalMessageInfo

func (m *DumpItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DumpItem) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type StoreReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreReq) Reset()         { *m = StoreReq{} }
func (m *StoreReq) String() string { return proto.CompactTextString(m) }
func (*StoreReq) ProtoMessage()    {}
func (*StoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *StoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreReq.Unmarshal(m, b)
}
func (m *StoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreReq.Marshal(b, m, deterministic)
}
func (m *StoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreReq.Merge(m, src)
}
func (m *StoreReq) XXX_Size() int {
	return xxx_messageInfo_StoreReq.Size(m)
}
func (m *StoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_StoreReq proto.InternalMessageInfo

func (m *StoreReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreReq) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StoreResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResp) Reset()         { *m = StoreResp{} }
func (m *StoreResp) String() string { return proto.CompactTextString(m) }
func (*StoreResp) ProtoMessage()    {}
func (*StoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *StoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResp.Unmarshal(m, b)
}
func (m *StoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResp.Marshal(b, m, deterministic)
}
func (m *StoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResp.Merge(m, src)
}
func (m *StoreResp) XXX_Size() int {
	return xxx_messageInfo_StoreResp.Size(m)
}
func (m *StoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResp proto.InternalMessageInfo

type GetReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResp struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (m *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(m, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*DumpReq)(nil), "grpcservice.DumpReq")
	proto.RegisterType((*DumpItem)(nil), "grpcservice.DumpItem")
	proto.RegisterType((*StoreReq)(nil), "grpcservice.StoreReq")
	proto.RegisterType((*StoreResp)(nil), "grpcservice.StoreResp")
	proto.RegisterType((*GetReq)(nil), "grpcservice.GetReq")
	proto.RegisterType((*GetResp)(nil), "grpcservice.GetResp")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0xb1, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x95, 0x38, 0xb9, 0xd8, 0x5d, 0x4a, 0x73, 0x0b, 0x82, 0x52, 0x0b, 0x95, 0xf4, 0xb8, 0x38,
	0x40, 0x4c, 0xcf, 0x92, 0xd4, 0x5c, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x10, 0x13, 0x24, 0x52, 0x96, 0x98, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x13, 0x04, 0x62, 0x2a, 0x19, 0x71, 0x71, 0x04, 0x97, 0xe4, 0x17, 0xa5, 0x06, 0xa5, 0x16, 0x62,
	0x51, 0x2f, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0xd5, 0x01, 0xe1, 0x28, 0x71, 0x73,
	0x71, 0x42, 0xf5, 0x14, 0x17, 0x28, 0x49, 0x71, 0xb1, 0xb9, 0xa7, 0x96, 0x60, 0xd5, 0xae, 0x24,
	0xcf, 0xc5, 0x0e, 0x96, 0x2b, 0x2e, 0x40, 0x98, 0xc4, 0x88, 0x64, 0x92, 0xd1, 0x56, 0x46, 0x2e,
	0x1e, 0xe7, 0xc4, 0xe4, 0x8c, 0xd4, 0x60, 0x88, 0x4f, 0x84, 0x2c, 0xb8, 0x58, 0xc1, 0x46, 0x0b,
	0x89, 0xea, 0x21, 0x79, 0x50, 0x0f, 0xe6, 0x44, 0x29, 0x31, 0x6c, 0xc2, 0xc5, 0x05, 0x4a, 0x0c,
	0x42, 0x46, 0x5c, 0xcc, 0xee, 0xa9, 0x25, 0x42, 0xc2, 0x28, 0x0a, 0x20, 0x2e, 0x93, 0x12, 0xc1,
	0x14, 0x04, 0xeb, 0x31, 0xe7, 0x62, 0x01, 0x05, 0x96, 0x10, 0xaa, 0x3c, 0x34, 0x28, 0xa5, 0x44,
	0x31, 0x44, 0x41, 0xa1, 0xaa, 0xc4, 0x60, 0xc0, 0x98, 0xc4, 0x06, 0x8e, 0x04, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x15, 0xd6, 0x2b, 0x36, 0x92, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheServiceClient interface {
	Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	Dump(ctx context.Context, in *DumpReq, opts ...grpc.CallOption) (CacheService_DumpClient, error)
}

type cacheServiceClient struct {
	cc *grpc.ClientConn
}

func NewCacheServiceClient(cc *grpc.ClientConn) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error) {
	out := new(StoreResp)
	err := c.cc.Invoke(ctx, "/grpcservice.CacheService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := c.cc.Invoke(ctx, "/grpcservice.CacheService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Dump(ctx context.Context, in *DumpReq, opts ...grpc.CallOption) (CacheService_DumpClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CacheService_serviceDesc.Streams[0], "/grpcservice.CacheService/Dump", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheServiceDumpClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CacheService_DumpClient interface {
	Recv() (*DumpItem, error)
	grpc.ClientStream
}

type cacheServiceDumpClient struct {
	grpc.ClientStream
}

func (x *cacheServiceDumpClient) Recv() (*DumpItem, error) {
	m := new(DumpItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CacheServiceServer is the server API for CacheService service.
type CacheServiceServer interface {
	Store(context.Context, *StoreReq) (*StoreResp, error)
	Get(context.Context, *GetReq) (*GetResp, error)
	Dump(*DumpReq, CacheService_DumpServer) error
}

// UnimplementedCacheServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCacheServiceServer struct {
}

func (*UnimplementedCacheServiceServer) Store(ctx context.Context, req *StoreReq) (*StoreResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedCacheServiceServer) Get(ctx context.Context, req *GetReq) (*GetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCacheServiceServer) Dump(req *DumpReq, srv CacheService_DumpServer) error {
	return status.Errorf(codes.Unimplemented, "method Dump not implemented")
}

func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&_CacheService_serviceDesc, srv)
}

func _CacheService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcservice.CacheService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Store(ctx, req.(*StoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcservice.CacheService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Dump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServiceServer).Dump(m, &cacheServiceDumpServer{stream})
}

type CacheService_DumpServer interface {
	Send(*DumpItem) error
	grpc.ServerStream
}

type cacheServiceDumpServer struct {
	grpc.ServerStream
}

func (x *cacheServiceDumpServer) Send(m *DumpItem) error {
	return x.ServerStream.SendMsg(m)
}

var _CacheService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcservice.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _CacheService_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CacheService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dump",
			Handler:       _CacheService_Dump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
